### ISSUE TITLE
Unable to run test suite due to conflicting thor versions

### ISSUE THREAD

**Issue by sbleon** [sonnym/js-asset_paths#19]
This is not urgent (for me anyway), but I'm not able to run the full test suite. Usually, several tests will pass, then I see:
```
/Users/leon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:317:in `check_for_activated_spec!': You have already activated thor 0.19.4, but your Gemfile requires thor 0.20.0. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
	from /Users/leon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:32:in `block in setup'
	from /Users/leon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/forwardable.rb:229:in `each'
	from /Users/leon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/forwardable.rb:229:in `each'
	from /Users/leon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:27:in `map'
	from /Users/leon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:27:in `setup'
	from /Users/leon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/inline.rb:72:in `gemfile'
	from test/support/bundlescript:4:in `<main>'
```

I've tried removing all versions of the `thor` gem and then running `bundle install`, but the problem persists, and I end up with both 0.19.4 and 0.20.0 installed afterwards.

**Comment by sonnym** [comment]
I see the same thing, but it does not break the test suit for me:
```
$ bundle exec rake test                                                                                                                                                                                                                                                      
/home/sonny/.rbenv/versions/2.4.1/bin/ruby -w -I"lib:lib/js_asset_paths" -I"/home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/rake-12.0.0/lib" "/home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "test/integration/bundler_gem_require_test.rb" "test/unit/dig
est_values_test.rb" "test/unit/engine_test.rb" "test/unit/generator_test.rb" "test/unit/js_asset_paths_test.rb" "test/unit/output_test.rb"                     
/home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/therubyracer-0.12.3/lib/v8/init.so: warning: method redefined; discarding old IntegerValue     
/home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/therubyracer-0.12.3/lib/v8/error.rb:43: warning: assigned but unused variable - trace_framework
/home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/therubyracer-0.12.3/lib/v8/error.rb:69: warning: `*' interpreted as argument prefix
/home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/therubyracer-0.12.3/lib/v8/error.rb:74: warning: `*' interpreted as argument prefix      
/home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/therubyracer-0.12.3/lib/v8/error.rb:64: warning: assigned but unused variable - backtrace                                                                
/home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/ref-2.0.0/lib/ref/abstract_reference_key_map.rb:145: warning: parentheses after method name is interpreted as an argument list, not a decomposed argument                                                                                                         
/home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/therubyracer-0.12.3/lib/v8/access/invocation.rb:16: warning: `*' interpreted as argument prefix
/home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/therubyracer-0.12.3/lib/v8/access/invocation.rb:27: warning: `*' interpreted as argument prefix
/home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/therubyracer-0.12.3/lib/v8/access/invocation.rb:31: warning: `*' interpreted as argument prefix
Run options: --seed 60029                                                                                                                       
                                                                                                                                                
# Running:                                                                                                                                            
                                                                                                                                                                                                                                                                                               
/home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:317:in `check_for_activated_spec!': You have already activated thor 0.19.4, but your Gemfile requires thor 0.20.0. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
        from /home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:32:in `block in setup'                      
        from /home/sonny/.rbenv/versions/2.4.1/lib64/ruby/2.4.0/forwardable.rb:229:in `each'                                                                
        from /home/sonny/.rbenv/versions/2.4.1/lib64/ruby/2.4.0/forwardable.rb:229:in `each'                               
        from /home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:27:in `map'  
        from /home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:27:in `setup'                                                                                                                                                                                                  
        from /home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/inline.rb:72:in `gemfile'            
        from test/support/bundlescript:4:in `<main>'                                                                                                                                                                                                                                                            
..................                                                                                                                                          
                                                                                                                                                
Finished in 5.014402s, 3.5897 runs/s, 3.5897 assertions/s.                                                                                      
18 runs, 18 assertions, 0 failures, 0 errors, 0 skips                                                                                                 
Coverage report generated for Integration Tests to /home/sonny/src/js-asset_paths/coverage. 121 / 122 LOC (99.18%) covered. 
```

After a `bundle update thor`, It looks much cleaner:
```
$ bundle exec rake test                                                                                                                                                                                                                                                      
/home/sonny/.rbenv/versions/2.4.1/bin/ruby -w -I"lib:lib/js_asset_paths" -I"/home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/rake-12.0.0/lib" "/home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "test/integration/bundler_gem_require_test.rb" "test/unit/dig
est_values_test.rb" "test/unit/engine_test.rb" "test/unit/generator_test.rb" "test/unit/js_asset_paths_test.rb" "test/unit/output_test.rb"                                                                                                                                                                                     
/home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/therubyracer-0.12.3/lib/v8/init.so: warning: method redefined; discarding old IntegerValue                                                                                                                                                                        
/home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/therubyracer-0.12.3/lib/v8/error.rb:43: warning: assigned but unused variable - trace_framework                                                                                                                                                                   
/home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/therubyracer-0.12.3/lib/v8/error.rb:69: warning: `*' interpreted as argument prefix                                                                                                                                                                               
/home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/therubyracer-0.12.3/lib/v8/error.rb:74: warning: `*' interpreted as argument prefix                                                                                                                                                                               
/home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/therubyracer-0.12.3/lib/v8/error.rb:64: warning: assigned but unused variable - backtrace                                                                                                                                                                         
/home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/ref-2.0.0/lib/ref/abstract_reference_key_map.rb:145: warning: parentheses after method name is interpreted as an argument list, not a decomposed argument                                                                                                         
/home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/therubyracer-0.12.3/lib/v8/access/invocation.rb:16: warning: `*' interpreted as argument prefix                                                                                                                                                                   
/home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/therubyracer-0.12.3/lib/v8/access/invocation.rb:27: warning: `*' interpreted as argument prefix                                                                                                                                                                   
/home/sonny/.rbenv/versions/2.4.1/lib64/ruby/gems/2.4.0/gems/therubyracer-0.12.3/lib/v8/access/invocation.rb:31: warning: `*' interpreted as argument prefix                                                                                                                                                                   
Run options: --seed 19349                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                               
# Running:                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                               
..................                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                               
Finished in 2.699728s, 6.6673 runs/s, 6.6673 assertions/s.                                                                                                                                                                                                                                                                     
18 runs, 18 assertions, 0 failures, 0 errors, 0 skips                                                                                                                                                                                                                                                                          
Coverage report generated for Integration Tests to /home/sonny/src/js-asset_paths/coverage. 121 / 122 LOC (99.18%) covered.
```

But it's still a mess, so this might be even better:
```
$ bundle exec rake test 2>/dev/null                                                                          
Run options: --seed 15339                                                      

# Running:                                                                     

..................                                                             

Finished in 4.754126s, 3.7862 runs/s, 3.7862 assertions/s.                     
18 runs, 18 assertions, 0 failures, 0 errors, 0 skips                          
Coverage report generated for Integration Tests to /home/sonny/src/js-asset_paths/coverage. 121 / 122 LOC (99.18%) covered.
```

**Comment by sbleon** [comment]
Ah, you're right. I was misreading the output. It finishes for me as well.
